---
abstract: 'Web content engine library for Gtk2'
author:
  - 'Florian Ragwitz  C<< <rafl@debian.org> >>'
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::PkgConfig: 0
  Glib::MakeHelper: 0
  Gtk2::CodeGen: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk2-WebKit
no_index:
  directory:
    - inc
    - ext
    - inc
    - t
requires:
  Gtk2: 0
  perl: 5.8.0
version: 0.04
