---
abstract: 'Web content engine library for Gtk2'
author:
  - 'Florian Ragwitz  C<< <rafl@debian.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::Depends: 0
  ExtUtils::MakeMaker: 6.42
  ExtUtils::PkgConfig: 0
  Glib::MakeHelper: 0
  Gtk2::CodeGen: 0
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk2-WebKit
no_index:
  directory:
    - ext
    - inc
    - t
provides:
  Gtk2::WebKit:
    file: lib/Gtk2/WebKit.pm
    version: 0.05
requires:
  Gtk2: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.05
